#ifndef _PPOLY_H_
#define _PPOLY_H_

#ifdef __cplusplus
extern "C" {
#endif

void    phonginterpola(signed long xx1, signed long yy1, signed long uu1, signed long vv1,
                       signed long xx2, signed long yy2, signed long uu2, signed long vv2);

#ifdef __cplusplus
}                                                            
#endif                                                       
#endif

